name: Project CI

on: 
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Make directory
      run: mkdir -p out

    - name: Build
      run: go build -o out ./cmd

    - name: Test
      run: go test ./...
      
    - name: Clean
      run: rm -rf out
